version: '3'

volumes:
  eero-client-data:
    name: eero-client-data
    external: true

services:
  eero-monitor:
    build: .
    container_name: eero-monitor
    env_file: .env
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - eero-client-data:/data
      - ./logs:/logs
      - ./scripts:/scripts
      - ./crontab:/etc/crontabs/root
    command: [ "run" ]
    # entrypoint: ["/bin/sh", "-c", "echo 'doing nothing . . .' && tail -f /dev/null"]
